### ISSUE TITLE
Segfault with -t

### ISSUE THREAD

**Issue by lkarsten** [varnish/hitch#22]
Running 1.0.0-beta2 on EL7:
```
[root@el7 hitch]# /usr/sbin/hitch-openssl -t --config=/etc/hitch/hitch.conf
Trying to initialize SSL contexts with your certificatesSegmentation fault

[root@el7 hitch]# /usr/sbin/hitch-openssl --config=/etc/hitch/hitch.conf -t
Trying to initialize SSL contexts with your certificatesSegmentation fault
```

```
[root@el7 hitch]# gdb --args /usr/sbin/hitch-openssl --config=/etc/hitch/hitch.conf -t
[..]
Program received signal SIGSEGV, Segmentation fault.
0x0000000000407f16 in load_cert_ctx ()
Missing separate debuginfos, use: debuginfo-install varnish-plus-addon-ssl-1.0.0-0beta2.el7.x86_64
(gdb) bt full
#0  0x0000000000407f16 in load_cert_ctx ()
No symbol table info available.
#1  0x000000000040b660 in init_openssl ()
No symbol table info available.
#2  0x00000000004076e6 in config_parse_cli ()
No symbol table info available.
#3  0x000000000040397a in main ()
No symbol table info available.
```

**Comment by daghf** [comment]
Could you try again with 7f549a35a379984a45e28b6e57d5f1e325c713b3?

**Comment by lkarsten** [comment]
Confirm that this is working fine on current master.
